<?php

$title = 'Quiz Home';
$this->headMeta()->appendName('keywords','Quiz, Home');
$this->headMeta()->appendName('description', 'Home of the best quizzes on the internet');
$this->headTitle($this->escapeHtml($title));

echo "<h1>Latest Quizzes</h1>";

if(count($this->quizzes) > 0):
    echo "<ul class='list-group'>";
    foreach($this->quizzes as $quiz):
?>
    <li class="list-group-item lh-condensed d-flex">
        <a href="<?= $this->url('quiz', ['action' => 'answer', 'id' => $quiz->getQuizId()]); ?>">
            <?= $quiz->getTitle();?>
        </a>
    </li>
<?php
    endforeach;
    echo "</ul>";
else:

    echo "No quizzes have been posted yet. Be the first to <a href='".$this->url('quiz', ['action' => 'create'])."'>create a quiz.</a>";
endif;
